**Задание:**

**1.** Построить модель мультиклассификации на основе логистической регрессии 

**2.** Выведите метрики модели: **accuracy**, **precision**, **recall**, **f1-score**. Допустимо ли в данной задаче использовать метрику **accuracy**?

**3.** Превратите задачу мультиклассификации в задачу бинарной классификации и постройте еще одну модель логистичекой регрессии, но уже для бинарной классификации. 

**4.** Сравните метрики качества бинарной и мультиклассовой классификации. Изменились ли существенно метрики бинарной классификации в сравнении мультиклассификацией? Подумайте и объясните, почему так произошло? Можно для объяснения использовать визуализацию

**5.** Написать функции, которые считают метрики **precision**, **recall**, **f1-score** (для бинарной классификации). Убедитесь, ято функции работают правильно, сравнив результаты их работы с метриками **classification_report** из библиотеки skelarn.

**Суммарное количество баллов: 15**

**Данные:**

В датасете представленны разничные характеристики телефонов (признаки) и их ценовая группа (столбец **price_range** -  целевая переменная). Необходимо спрогнозировать, к какому классу по стоимости относится телефон.

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LogisticRegression as LogR
from sklearn.metrics import accuracy_score, f1_score, classification_report, roc_auc_score, confusion_matrix
from sklearn.preprocessing import MinMaxScaler, RobustScaler

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv('drive/My Drive/PhoneClassification.csv')
data.head()

Mounted at /content/drive


battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [ ]:
x = data[['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g', 'int_memory', 'm_dep', 'mobile_wt',
          'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g', 'touch_screen', 'wifi']]
y = data['price_range']

x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.3, random_state = 34)
log_res = LogR(solver='sag', max_iter=10000)
model = log_res.fit(x_train, y_train)
pred_train = model.predict(x_train)
pred_train

array([1, 0, 2, ..., 0, 2, 2])

In [ ]:
pred_train_proba = model.predict_proba(x_train)
pred_train_proba

array([[7.41735185e-03, 5.19746461e-01, 4.27396789e-01, 4.54393978e-02],
       [9.53784514e-01, 4.57010989e-02, 5.12938772e-04, 1.44849376e-06],
       [1.15391655e-05, 3.78002252e-02, 5.27585284e-01, 4.34602951e-01],
       ...,
       [7.47554191e-01, 2.42522054e-01, 9.88084647e-03, 4.29077846e-05],
       [6.02205166e-04, 1.88383547e-01, 6.42677721e-01, 1.68336527e-01],
       [5.25295604e-05, 5.16099078e-02, 5.76771206e-01, 3.71566356e-01]])

In [ ]:
pred_test = model.predict(x_test)
pred_test

array([0, 3, 0, 1, 1, 0, 1, 1, 3, 2, 2, 0, 0, 0, 1, 3, 2, 0, 1, 1, 1, 2,
       3, 3, 3, 0, 1, 3, 3, 2, 1, 3, 3, 0, 3, 0, 3, 0, 2, 1, 1, 0, 3, 3,
       3, 2, 2, 0, 0, 1, 3, 1, 2, 2, 3, 1, 2, 3, 0, 2, 2, 1, 1, 3, 3, 2,
       0, 0, 0, 1, 2, 0, 0, 3, 1, 2, 1, 1, 3, 1, 0, 1, 3, 0, 2, 3, 2, 3,
       2, 3, 1, 1, 1, 1, 2, 3, 1, 0, 3, 1, 1, 3, 0, 0, 1, 2, 1, 3, 0, 3,
       1, 3, 3, 2, 3, 1, 2, 1, 0, 3, 2, 1, 3, 2, 2, 2, 0, 3, 0, 1, 3, 3,
       1, 1, 3, 0, 0, 2, 3, 1, 3, 1, 0, 0, 2, 3, 3, 3, 2, 1, 3, 1, 3, 3,
       3, 3, 1, 2, 1, 2, 1, 0, 3, 0, 3, 3, 3, 3, 3, 1, 0, 2, 3, 0, 0, 1,
       2, 2, 2, 0, 1, 1, 0, 3, 3, 0, 2, 0, 0, 2, 3, 0, 3, 3, 0, 3, 1, 3,
       3, 0, 2, 3, 1, 0, 1, 0, 1, 3, 1, 2, 3, 2, 2, 1, 2, 3, 2, 2, 1, 3,
       3, 0, 2, 0, 3, 0, 1, 2, 0, 0, 3, 1, 3, 0, 3, 2, 2, 0, 3, 1, 1, 3,
       0, 0, 0, 1, 1, 0, 2, 0, 0, 2, 1, 3, 1, 2, 0, 1, 1, 3, 0, 0, 1, 1,
       2, 2, 1, 1, 3, 1, 1, 3, 0, 3, 1, 2, 3, 3, 1, 3, 3, 3, 1, 0, 0, 1,
       0, 3, 2, 0, 1, 0, 0, 3, 3, 1, 1, 3, 3, 2, 2,

In [ ]:
pred_test_proba = model.predict_proba(x_test)
pred_test_proba

array([[6.08118464e-01, 3.66248392e-01, 2.54635752e-02, 1.69569501e-04],
       [6.07361084e-09, 1.00864353e-03, 7.93548900e-02, 9.19636460e-01],
       [9.62503209e-01, 3.72125499e-02, 2.83647437e-04, 5.93935508e-07],
       ...,
       [1.06289489e-03, 2.01387378e-01, 6.20119029e-01, 1.77430698e-01],
       [4.35551966e-03, 4.17016362e-01, 5.00504807e-01, 7.81233115e-02],
       [7.37890322e-02, 6.83791301e-01, 2.29374483e-01, 1.30451842e-02]])

## Метрики к модели мультиклассификации

In [ ]:
print('Metrics for train:\n ', classification_report(y_train, pred_train))

Metrics for train:
                precision    recall  f1-score   support

           0       0.88      0.86      0.87       345
           1       0.65      0.66      0.65       340
           2       0.57      0.54      0.56       352
           3       0.74      0.80      0.77       363

    accuracy                           0.71      1400
   macro avg       0.71      0.71      0.71      1400
weighted avg       0.71      0.71      0.71      1400



In [ ]:
print('Metrics for test:\n ', classification_report(y_test, pred_test))

Metrics for test:
                precision    recall  f1-score   support

           0       0.82      0.84      0.83       155
           1       0.66      0.59      0.62       160
           2       0.58      0.51      0.54       148
           3       0.69      0.85      0.76       137

    accuracy                           0.69       600
   macro avg       0.69      0.70      0.69       600
weighted avg       0.69      0.69      0.69       600



## Бинарная классификация


In [ ]:
data_bin = data.copy()

In [ ]:
def isExpensive(x):
  if x > 1:
    return 1
  else:
    return 0
isExpensive(2)

1

In [ ]:
data_bin['expensive'] = data_bin['price_range'].apply(isExpensive)
data_bin

battery_power  blue  clock_speed  ...  wifi  price_range  expensive
0               842     0          2.2  ...     1            1          0
1              1021     1          0.5  ...     0            2          1
2               563     1          0.5  ...     0            2          1
3               615     1          2.5  ...     0            2          1
4              1821     1          1.2  ...     0            1          0
...             ...   ...          ...  ...   ...          ...        ...
1995            794     1          0.5  ...     0            0          0
1996           1965     1          2.6  ...     1            2          1
1997           1911     0          0.9  ...     0            3          1
1998           1512     0          0.9  ...     1            0          0
1999            510     1          2.0  ...     1            3          1

[2000 rows x 22 columns]

In [ ]:
x = data_bin[['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g', 'int_memory', 'm_dep', 'mobile_wt',
          'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g', 'touch_screen', 'wifi']]
y = data_bin['expensive']

x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.3, random_state = 34)
log_res = LogR(solver='sag', max_iter=10000)
model = log_res.fit(x_train, y_train)
pred_train = model.predict(x_train)
pred_train

array([0, 0, 1, ..., 0, 1, 1])

In [ ]:
pred_train_proba = model.predict_proba(x_train)
pred_train_proba

array([[0.50395541, 0.49604459],
       [0.99663764, 0.00336236],
       [0.03331767, 0.96668233],
       ...,
       [0.98706014, 0.01293986],
       [0.16508268, 0.83491732],
       [0.05131074, 0.94868926]])

In [ ]:
pred_test = model.predict(x_test)
pred_test

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,

In [ ]:
pred_test_proba = model.predict_proba(x_test)
pred_test_proba

array([[0.97052937, 0.02947063],
       [0.00220768, 0.99779232],
       [0.99766148, 0.00233852],
       ...,
       [0.20538654, 0.79461346],
       [0.36248038, 0.63751962],
       [0.7902102 , 0.2097898 ]])

## Метрики для бинарной классификации

In [ ]:
print('Metrics for train:\n ', classification_report(y_train, pred_train))

Metrics for train:
                precision    recall  f1-score   support

           0       0.91      0.87      0.89       685
           1       0.88      0.92      0.90       715

    accuracy                           0.89      1400
   macro avg       0.89      0.89      0.89      1400
weighted avg       0.89      0.89      0.89      1400



In [ ]:
print('Metrics for test:\n ', classification_report(y_test, pred_test))

Metrics for test:
                precision    recall  f1-score   support

           0       0.93      0.87      0.90       315
           1       0.86      0.92      0.89       285

    accuracy                           0.89       600
   macro avg       0.89      0.89      0.89       600
weighted avg       0.90      0.89      0.89       600



Вывод: для бинарной классификации показатели метрик выше, так как вероятность распределения элемента в неправильный класс меньше из-за количества этих классов (было 4, стало 2)

## Собственные функции для подсчета метрик

In [ ]:
tp = sum((y_test == 1) & (pred_test == 1))
fp = sum((y_test == 0) & (pred_test == 1))
tn = sum((y_test == 0) & (pred_test == 0))
fn = sum((y_test == 1) & (pred_test == 0)) 
print(tp, fp, tn, fn)

263 42 273 22


In [ ]:
def new_accuracy(tp, fp, tn, fn):
  return (tp+tn)/(tp+tn+fp+fn)

new_accuracy(tp, fp, tn, fn)

0.8933333333333333

In [ ]:
def new_precision(tp, fp):
  return tp/(tp+fp)

new_precision(tp, fp)

0.8622950819672132

In [ ]:
def new_recall(tp, fn):
  return tp/(tp+fn)

new_recall(tp, fn)

0.9228070175438596

In [ ]:
def new_f1(tp, fp, fn):
  return (2 * new_precision(tp, fp) * new_recall(tp, fn))/(new_precision(tp, fp) + new_recall(tp, fn))

new_f1(tp, fp, fn)

0.8915254237288136

Функции выдали верный результат

## Модель с учетом нормализации и стандартизации

In [ ]:
min_max = MinMaxScaler()
min_max.fit(x_train)
x_train_min_max = min_max.transform(x_train)
x_test_min_max = min_max.transform(x_test)

In [ ]:
lr = LogR(solver = "sag", max_iter = 10000)
model_mm = lr.fit(x_train_min_max, y_train)
pred_min_max = model_mm.predict(x_test_min_max)

print(classification_report(y_test, pred_min_max))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       315
           1       1.00      1.00      1.00       285

    accuracy                           1.00       600
   macro avg       1.00      1.00      1.00       600
weighted avg       1.00      1.00      1.00       600



In [ ]:
x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.6, random_state = 34)

min_max.fit(x_train)
x_train_min_max = min_max.transform(x_train)
x_test_min_max = min_max.transform(x_test)

model_mm = lr.fit(x_train_min_max, y_train)
pred_min_max = model_mm.predict(x_test_min_max)

print(classification_report(y_test, pred_min_max))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96       615
           1       0.95      0.98      0.96       585

    accuracy                           0.96      1200
   macro avg       0.96      0.96      0.96      1200
weighted avg       0.96      0.96      0.96      1200



In [ ]:
robust = RobustScaler()
robust.fit(x_train)
x_train_robust = robust.transform(x_train)
x_test_robust = robust.transform(x_test)

model_rob = lr.fit(x_train_robust, y_train)
pred_rob = model_rob.predict(x_test_robust)

print(classification_report(y_test, pred_rob))

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       615
           1       0.96      0.98      0.97       585

    accuracy                           0.97      1200
   macro avg       0.97      0.97      0.97      1200
weighted avg       0.97      0.97      0.97      1200

